//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vectornav
{
    [Serializable]
    public class DeltaGroupMsg : Message
    {
        public const string k_RosMessageName = "vectornav_msgs/DeltaGroup";
        public override string RosMessageName => k_RosMessageName;

        //  Custom msg field added by Mecatron
        //  Used to preserve the dtheta, dtime and dvel sent by the IMU
        public Std.HeaderMsg header;
        public float deltatheta_dtime;
        public Geometry.Vector3Msg deltatheta_dtheta;
        public Geometry.Vector3Msg deltatheta_dvel;

        public DeltaGroupMsg()
        {
            this.header = new Std.HeaderMsg();
            this.deltatheta_dtime = 0.0f;
            this.deltatheta_dtheta = new Geometry.Vector3Msg();
            this.deltatheta_dvel = new Geometry.Vector3Msg();
        }

        public DeltaGroupMsg(Std.HeaderMsg header, float deltatheta_dtime, Geometry.Vector3Msg deltatheta_dtheta, Geometry.Vector3Msg deltatheta_dvel)
        {
            this.header = header;
            this.deltatheta_dtime = deltatheta_dtime;
            this.deltatheta_dtheta = deltatheta_dtheta;
            this.deltatheta_dvel = deltatheta_dvel;
        }

        public static DeltaGroupMsg Deserialize(MessageDeserializer deserializer) => new DeltaGroupMsg(deserializer);

        private DeltaGroupMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.deltatheta_dtime);
            this.deltatheta_dtheta = Geometry.Vector3Msg.Deserialize(deserializer);
            this.deltatheta_dvel = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.deltatheta_dtime);
            serializer.Write(this.deltatheta_dtheta);
            serializer.Write(this.deltatheta_dvel);
        }

        public override string ToString()
        {
            return "DeltaGroupMsg: " +
            "\nheader: " + header.ToString() +
            "\ndeltatheta_dtime: " + deltatheta_dtime.ToString() +
            "\ndeltatheta_dtheta: " + deltatheta_dtheta.ToString() +
            "\ndeltatheta_dvel: " + deltatheta_dvel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
