//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class DetectionFlagMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/DetectionFlag";
        public override string RosMessageName => k_RosMessageName;

        //  Beam is OK
        public const byte DETECT_OK = 0;
        //  Beam is flagged as bad by the sonar.  Think hard before second-guessing
        public const byte DETECT_BAD_SONAR = 1;
        //  Beam is flagged as bad by some automated filter applied during processing.
        public const byte DETECT_BAD_FILTER = 2;
        //  Beam is flagged as bad by the user. This is probably not happening in
        //  realtime, but is included here so the same message can be used throughout
        //  a post-processing pipeline.
        public const byte DETECT_BAD_USER = 4;
        //  These arrays should have the same dimensions, and should match
        //  the number of beams for this sonar.
        // 
        //  Some fields are optional.  Those should have 0 length.
        //  Flag values for every beam
        public byte flag;

        public DetectionFlagMsg()
        {
            this.flag = 0;
        }

        public DetectionFlagMsg(byte flag)
        {
            this.flag = flag;
        }

        public static DetectionFlagMsg Deserialize(MessageDeserializer deserializer) => new DetectionFlagMsg(deserializer);

        private DetectionFlagMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.flag);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.flag);
        }

        public override string ToString()
        {
            return "DetectionFlagMsg: " +
            "\nflag: " + flag.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
