//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class PingInfoMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/PingInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Center frequency of sonar in Hz
        //  Set to 0 if unavailable
        public float frequency;
        //  Speed of sound (m/s) used to calculate ranges;
        //  Set to 0 if unavailable
        public float sound_speed;
        //  Sonar reported -3db beamwidths
        //  May be empty if not reported
        //  reported in radians
        public float[] tx_beamwidths;
        public float[] rx_beamwidths;

        public PingInfoMsg()
        {
            this.frequency = 0.0f;
            this.sound_speed = 0.0f;
            this.tx_beamwidths = new float[0];
            this.rx_beamwidths = new float[0];
        }

        public PingInfoMsg(float frequency, float sound_speed, float[] tx_beamwidths, float[] rx_beamwidths)
        {
            this.frequency = frequency;
            this.sound_speed = sound_speed;
            this.tx_beamwidths = tx_beamwidths;
            this.rx_beamwidths = rx_beamwidths;
        }

        public static PingInfoMsg Deserialize(MessageDeserializer deserializer) => new PingInfoMsg(deserializer);

        private PingInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.sound_speed);
            deserializer.Read(out this.tx_beamwidths, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.rx_beamwidths, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frequency);
            serializer.Write(this.sound_speed);
            serializer.WriteLength(this.tx_beamwidths);
            serializer.Write(this.tx_beamwidths);
            serializer.WriteLength(this.rx_beamwidths);
            serializer.Write(this.rx_beamwidths);
        }

        public override string ToString()
        {
            return "PingInfoMsg: " +
            "\nfrequency: " + frequency.ToString() +
            "\nsound_speed: " + sound_speed.ToString() +
            "\ntx_beamwidths: " + System.String.Join(", ", tx_beamwidths.ToList()) +
            "\nrx_beamwidths: " + System.String.Join(", ", rx_beamwidths.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
