//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class ProjectedSonarImageMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/ProjectedSonarImage";
        public override string RosMessageName => k_RosMessageName;

        //  Single scan from an imaging sonar
        // 
        //  The Z-axis is centered in the plane of the fan ("forward"), with X up,
        //  in order to be consistent with the NED for traditional multibeam profilers.
        // 
        //  For sonars with a 1D array, the beams lie on the Y-Z plane, and
        //  and each beam has an azimuth (rotation about X) value.  Zero azimuth
        //  is in the direction of the Z-axis, typically "straight out" from the sonar.
        //  Elevation is the orthogonal direction (rotation about Y),
        //  often termed the "vertical aperture"
        //  The header time should be the time the ping was transmitted, not
        //  the time the message was received.
        //  Note that these two could potentially be several seconds apart,
        //  especially in deep water.
        public Std.HeaderMsg header;
        public PingInfoMsg ping_info;
        public Geometry.Vector3Msg[] beam_directions;
        //  Center of each range bin in meters. Note this these may not be equally
        //  spaced, and do not necessarily start at zero range.
        public float[] ranges;
        public SonarImageDataMsg image;

        public ProjectedSonarImageMsg()
        {
            this.header = new Std.HeaderMsg();
            this.ping_info = new PingInfoMsg();
            this.beam_directions = new Geometry.Vector3Msg[0];
            this.ranges = new float[0];
            this.image = new SonarImageDataMsg();
        }

        public ProjectedSonarImageMsg(Std.HeaderMsg header, PingInfoMsg ping_info, Geometry.Vector3Msg[] beam_directions, float[] ranges, SonarImageDataMsg image)
        {
            this.header = header;
            this.ping_info = ping_info;
            this.beam_directions = beam_directions;
            this.ranges = ranges;
            this.image = image;
        }

        public static ProjectedSonarImageMsg Deserialize(MessageDeserializer deserializer) => new ProjectedSonarImageMsg(deserializer);

        private ProjectedSonarImageMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.ping_info = PingInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.beam_directions, Geometry.Vector3Msg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.ranges, sizeof(float), deserializer.ReadLength());
            this.image = SonarImageDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.ping_info);
            serializer.WriteLength(this.beam_directions);
            serializer.Write(this.beam_directions);
            serializer.WriteLength(this.ranges);
            serializer.Write(this.ranges);
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "ProjectedSonarImageMsg: " +
            "\nheader: " + header.ToString() +
            "\nping_info: " + ping_info.ToString() +
            "\nbeam_directions: " + System.String.Join(", ", beam_directions.ToList()) +
            "\nranges: " + System.String.Join(", ", ranges.ToList()) +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
