//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class RawSonarImageMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/RawSonarImage";
        public override string RosMessageName => k_RosMessageName;

        //  The header time should be the time the ping was transmitted, not
        //  the time the message was received.
        //  Note that these two could potentially be several seconds apart,
        //  especially in deep water.
        public Std.HeaderMsg header;
        public PingInfoMsg ping_info;
        public float sample_rate;
        //  hz
        public uint samples_per_beam;
        //  the number of samples in each beam
        //  Many sonars have some kind of upper gate for water column data
        //  this represents the sample number of the first non empty sample
        //  for beam n
        public uint sample0;
        //  Multi-sector multibeams can transmit different sectors at different times
        //  The Reson doesn't but we include a TX delay for each beam anyway.
        // 
        //  Overall, therefore, our overall time is:
        // 
        //  header.stamp: TX cycle starts
        //  Each beam's TX time: header.stamp + transmit_delay[i]
        //  Each beam's RX time: header.stamp + transmit_delay[i] + sample_rate*image_row
        public float[] tx_delays;
        //  Steering angle applied to tx beam
        //  reported in radians
        public float[] tx_angles;
        //  Steering angle applied to rx beam
        //  reported in radians
        public float[] rx_angles;
        public SonarImageDataMsg image;

        public RawSonarImageMsg()
        {
            this.header = new Std.HeaderMsg();
            this.ping_info = new PingInfoMsg();
            this.sample_rate = 0.0f;
            this.samples_per_beam = 0;
            this.sample0 = 0;
            this.tx_delays = new float[0];
            this.tx_angles = new float[0];
            this.rx_angles = new float[0];
            this.image = new SonarImageDataMsg();
        }

        public RawSonarImageMsg(Std.HeaderMsg header, PingInfoMsg ping_info, float sample_rate, uint samples_per_beam, uint sample0, float[] tx_delays, float[] tx_angles, float[] rx_angles, SonarImageDataMsg image)
        {
            this.header = header;
            this.ping_info = ping_info;
            this.sample_rate = sample_rate;
            this.samples_per_beam = samples_per_beam;
            this.sample0 = sample0;
            this.tx_delays = tx_delays;
            this.tx_angles = tx_angles;
            this.rx_angles = rx_angles;
            this.image = image;
        }

        public static RawSonarImageMsg Deserialize(MessageDeserializer deserializer) => new RawSonarImageMsg(deserializer);

        private RawSonarImageMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.ping_info = PingInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.sample_rate);
            deserializer.Read(out this.samples_per_beam);
            deserializer.Read(out this.sample0);
            deserializer.Read(out this.tx_delays, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.tx_angles, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.rx_angles, sizeof(float), deserializer.ReadLength());
            this.image = SonarImageDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.ping_info);
            serializer.Write(this.sample_rate);
            serializer.Write(this.samples_per_beam);
            serializer.Write(this.sample0);
            serializer.WriteLength(this.tx_delays);
            serializer.Write(this.tx_delays);
            serializer.WriteLength(this.tx_angles);
            serializer.Write(this.tx_angles);
            serializer.WriteLength(this.rx_angles);
            serializer.Write(this.rx_angles);
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "RawSonarImageMsg: " +
            "\nheader: " + header.ToString() +
            "\nping_info: " + ping_info.ToString() +
            "\nsample_rate: " + sample_rate.ToString() +
            "\nsamples_per_beam: " + samples_per_beam.ToString() +
            "\nsample0: " + sample0.ToString() +
            "\ntx_delays: " + System.String.Join(", ", tx_delays.ToList()) +
            "\ntx_angles: " + System.String.Join(", ", tx_angles.ToList()) +
            "\nrx_angles: " + System.String.Join(", ", rx_angles.ToList()) +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
