//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class SonarRangesMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/SonarRanges";
        public override string RosMessageName => k_RosMessageName;

        //  Single ping from a profiling sonar.
        // 
        //  This message is modeled after WHOI's MultibeamRaw.msg, from the
        //  ds_multibeam_msgs package (released under a BSD license).
        //  Modifications were made by UW-APL.
        //  The header time should be the time the ping was transmitted, not
        //  the time the message was received.
        //  Note that these two could potentially be several seconds apart,
        //  especially in deep water.
        public Std.HeaderMsg header;
        public PingInfoMsg ping_info;
        //  Constants declaring whether each beam is good or bad.
        //  This is implemented as an 8-bit masked value; it is possible for more
        //  than one thing to flag beams as bad. To check if a beam is good, simply
        //  check if it is zero.
        public DetectionFlagMsg[] flags;
        //  Multi-sector multibeams can transmit different sectors at different times
        //  The Reson doesn't but we include a TX delay for each beam anyway.
        // 
        //  Overall, therefore, our overall time is:
        // 
        //  header.stamp: TX cycle starts
        //  Each beam's TX time: header.stamp + txDelay[i]
        //  Each beam's RX time: header.stamp + txDelay[i] + twowayTravelTime[i]
        public float[] transmit_delays;
        //  Sonar-reported intensity.  Usually uncalibrated and crude
        public float[] intensities;
        public Geometry.Vector3Msg[] beam_unit_vec;
        public float[] ranges;

        public SonarRangesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.ping_info = new PingInfoMsg();
            this.flags = new DetectionFlagMsg[0];
            this.transmit_delays = new float[0];
            this.intensities = new float[0];
            this.beam_unit_vec = new Geometry.Vector3Msg[0];
            this.ranges = new float[0];
        }

        public SonarRangesMsg(Std.HeaderMsg header, PingInfoMsg ping_info, DetectionFlagMsg[] flags, float[] transmit_delays, float[] intensities, Geometry.Vector3Msg[] beam_unit_vec, float[] ranges)
        {
            this.header = header;
            this.ping_info = ping_info;
            this.flags = flags;
            this.transmit_delays = transmit_delays;
            this.intensities = intensities;
            this.beam_unit_vec = beam_unit_vec;
            this.ranges = ranges;
        }

        public static SonarRangesMsg Deserialize(MessageDeserializer deserializer) => new SonarRangesMsg(deserializer);

        private SonarRangesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.ping_info = PingInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.flags, DetectionFlagMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.transmit_delays, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.intensities, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.beam_unit_vec, Geometry.Vector3Msg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.ranges, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.ping_info);
            serializer.WriteLength(this.flags);
            serializer.Write(this.flags);
            serializer.WriteLength(this.transmit_delays);
            serializer.Write(this.transmit_delays);
            serializer.WriteLength(this.intensities);
            serializer.Write(this.intensities);
            serializer.WriteLength(this.beam_unit_vec);
            serializer.Write(this.beam_unit_vec);
            serializer.WriteLength(this.ranges);
            serializer.Write(this.ranges);
        }

        public override string ToString()
        {
            return "SonarRangesMsg: " +
            "\nheader: " + header.ToString() +
            "\nping_info: " + ping_info.ToString() +
            "\nflags: " + System.String.Join(", ", flags.ToList()) +
            "\ntransmit_delays: " + System.String.Join(", ", transmit_delays.ToList()) +
            "\nintensities: " + System.String.Join(", ", intensities.ToList()) +
            "\nbeam_unit_vec: " + System.String.Join(", ", beam_unit_vec.ToList()) +
            "\nranges: " + System.String.Join(", ", ranges.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
