//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class SonarDetectionsMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/SonarDetections";
        public override string RosMessageName => k_RosMessageName;

        //  Single ping from a multibeam sonar.
        // 
        //  This message is modeled after WHOI's MultibeamRaw.msg, from the
        //  ds_multibeam_msgs package (released under a BSD license).
        //  Modifications were made by UW-APL.
        //  The header time should be the time the ping was transmitted, not
        //  the time the message was received.
        //  Note that these two could potentially be several seconds apart,
        //  especially in deep water.
        public Std.HeaderMsg header;
        public PingInfoMsg ping_info;
        //  Constants declaring whether each beam is good or bad.
        //  This is implemented as an 8-bit masked value; it is possible for more
        //  than one thing to flag beams as bad. To check if a beam is good, simply
        //  check if it is zero.
        public DetectionFlagMsg[] flags;
        //  Truly raw multibeam data uses travel times rather than ranges.
        //  reported in seconds
        public float[] two_way_travel_times;
        //  Multi-sector multibeams can transmit different sectors at different times
        //  The Reson doesn't but we include a TX delay for each beam anyway.
        // 
        //  Overall, therefore, our overall time is:
        // 
        //  header.stamp: TX cycle starts
        //  Each beam's TX time: header.stamp + txDelay[i]
        //  Each beam's RX time: header.stamp + txDelay[i] + twowayTravelTime[i]
        //  reported in seconds
        public float[] tx_delays;
        //  Sonar-reported intensity.  Usually uncalibrated and crude
        public float[] intensities;
        //  Sonar-reported along-track steering angle (applied to tx beam)
        //  + forward, - aft for a downlooking sonar
        //  reported in radians
        public float[] tx_angles;
        //  Sonar-reported across-track steering angle (applied to rx beam)
        //  + to starboard, - to port for a downlooking sonar
        //  reported in radians
        public float[] rx_angles;

        public SonarDetectionsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.ping_info = new PingInfoMsg();
            this.flags = new DetectionFlagMsg[0];
            this.two_way_travel_times = new float[0];
            this.tx_delays = new float[0];
            this.intensities = new float[0];
            this.tx_angles = new float[0];
            this.rx_angles = new float[0];
        }

        public SonarDetectionsMsg(Std.HeaderMsg header, PingInfoMsg ping_info, DetectionFlagMsg[] flags, float[] two_way_travel_times, float[] tx_delays, float[] intensities, float[] tx_angles, float[] rx_angles)
        {
            this.header = header;
            this.ping_info = ping_info;
            this.flags = flags;
            this.two_way_travel_times = two_way_travel_times;
            this.tx_delays = tx_delays;
            this.intensities = intensities;
            this.tx_angles = tx_angles;
            this.rx_angles = rx_angles;
        }

        public static SonarDetectionsMsg Deserialize(MessageDeserializer deserializer) => new SonarDetectionsMsg(deserializer);

        private SonarDetectionsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.ping_info = PingInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.flags, DetectionFlagMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.two_way_travel_times, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.tx_delays, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.intensities, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.tx_angles, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.rx_angles, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.ping_info);
            serializer.WriteLength(this.flags);
            serializer.Write(this.flags);
            serializer.WriteLength(this.two_way_travel_times);
            serializer.Write(this.two_way_travel_times);
            serializer.WriteLength(this.tx_delays);
            serializer.Write(this.tx_delays);
            serializer.WriteLength(this.intensities);
            serializer.Write(this.intensities);
            serializer.WriteLength(this.tx_angles);
            serializer.Write(this.tx_angles);
            serializer.WriteLength(this.rx_angles);
            serializer.Write(this.rx_angles);
        }

        public override string ToString()
        {
            return "SonarDetectionsMsg: " +
            "\nheader: " + header.ToString() +
            "\nping_info: " + ping_info.ToString() +
            "\nflags: " + System.String.Join(", ", flags.ToList()) +
            "\ntwo_way_travel_times: " + System.String.Join(", ", two_way_travel_times.ToList()) +
            "\ntx_delays: " + System.String.Join(", ", tx_delays.ToList()) +
            "\nintensities: " + System.String.Join(", ", intensities.ToList()) +
            "\ntx_angles: " + System.String.Join(", ", tx_angles.ToList()) +
            "\nrx_angles: " + System.String.Join(", ", rx_angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
