//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MarineAcoustic
{
    [Serializable]
    public class SonarImageDataMsg : Message
    {
        public const string k_RosMessageName = "marine_acoustic_msgs/SonarImageData";
        public override string RosMessageName => k_RosMessageName;

        public bool is_bigendian;
        public const uint DTYPE_UINT8 = 0;
        public const uint DTYPE_INT8 = 1;
        public const uint DTYPE_UINT16 = 2;
        public const uint DTYPE_INT16 = 3;
        public const uint DTYPE_UINT32 = 4;
        public const uint DTYPE_INT32 = 5;
        public const uint DTYPE_UINT64 = 6;
        public const uint DTYPE_INT64 = 7;
        public const uint DTYPE_FLOAT32 = 8;
        public const uint DTYPE_FLOAT64 = 9;
        public uint dtype;
        //  the number of beams associated with the image
        public uint beam_count;
        //  The actually pixel data in row-major (beam_index major) format
        public byte[] data;

        public SonarImageDataMsg()
        {
            this.is_bigendian = false;
            this.dtype = 0;
            this.beam_count = 0;
            this.data = new byte[0];
        }

        public SonarImageDataMsg(bool is_bigendian, uint dtype, uint beam_count, byte[] data)
        {
            this.is_bigendian = is_bigendian;
            this.dtype = dtype;
            this.beam_count = beam_count;
            this.data = data;
        }

        public static SonarImageDataMsg Deserialize(MessageDeserializer deserializer) => new SonarImageDataMsg(deserializer);

        private SonarImageDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_bigendian);
            deserializer.Read(out this.dtype);
            deserializer.Read(out this.beam_count);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_bigendian);
            serializer.Write(this.dtype);
            serializer.Write(this.beam_count);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SonarImageDataMsg: " +
            "\nis_bigendian: " + is_bigendian.ToString() +
            "\ndtype: " + dtype.ToString() +
            "\nbeam_count: " + beam_count.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
