//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class ChangeStateRequest : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/ChangeState";
        public override string RosMessageName => k_RosMessageName;

        //  The requested transition.
        // 
        //  This change state service will fail if the transition is not possible.
        public TransitionMsg transition;

        public ChangeStateRequest()
        {
            this.transition = new TransitionMsg();
        }

        public ChangeStateRequest(TransitionMsg transition)
        {
            this.transition = transition;
        }

        public static ChangeStateRequest Deserialize(MessageDeserializer deserializer) => new ChangeStateRequest(deserializer);

        private ChangeStateRequest(MessageDeserializer deserializer)
        {
            this.transition = TransitionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.transition);
        }

        public override string ToString()
        {
            return "ChangeStateRequest: " +
            "\ntransition: " + transition.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
