//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class ChangeStateResponse : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/ChangeState";
        public override string RosMessageName => k_RosMessageName;

        //  Indicates whether the service was able to initiate the state transition
        public bool success;

        public ChangeStateResponse()
        {
            this.success = false;
        }

        public ChangeStateResponse(bool success)
        {
            this.success = success;
        }

        public static ChangeStateResponse Deserialize(MessageDeserializer deserializer) => new ChangeStateResponse(deserializer);

        private ChangeStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ChangeStateResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
