//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class GetAvailableStatesResponse : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/GetAvailableStates";
        public override string RosMessageName => k_RosMessageName;

        //  Array of possible states that can be transitioned to.
        public StateMsg[] available_states;

        public GetAvailableStatesResponse()
        {
            this.available_states = new StateMsg[0];
        }

        public GetAvailableStatesResponse(StateMsg[] available_states)
        {
            this.available_states = available_states;
        }

        public static GetAvailableStatesResponse Deserialize(MessageDeserializer deserializer) => new GetAvailableStatesResponse(deserializer);

        private GetAvailableStatesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.available_states, StateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.available_states);
            serializer.Write(this.available_states);
        }

        public override string ToString()
        {
            return "GetAvailableStatesResponse: " +
            "\navailable_states: " + System.String.Join(", ", available_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
