//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class GetAvailableStatesRequest : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/GetAvailableStates";
        public override string RosMessageName => k_RosMessageName;


        public GetAvailableStatesRequest()
        {
        }
        public static GetAvailableStatesRequest Deserialize(MessageDeserializer deserializer) => new GetAvailableStatesRequest(deserializer);

        private GetAvailableStatesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetAvailableStatesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
