//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class GetAvailableTransitionsResponse : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/GetAvailableTransitions";
        public override string RosMessageName => k_RosMessageName;

        //  An array of the possible start_state-goal_state transitions
        public TransitionDescriptionMsg[] available_transitions;

        public GetAvailableTransitionsResponse()
        {
            this.available_transitions = new TransitionDescriptionMsg[0];
        }

        public GetAvailableTransitionsResponse(TransitionDescriptionMsg[] available_transitions)
        {
            this.available_transitions = available_transitions;
        }

        public static GetAvailableTransitionsResponse Deserialize(MessageDeserializer deserializer) => new GetAvailableTransitionsResponse(deserializer);

        private GetAvailableTransitionsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.available_transitions, TransitionDescriptionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.available_transitions);
            serializer.Write(this.available_transitions);
        }

        public override string ToString()
        {
            return "GetAvailableTransitionsResponse: " +
            "\navailable_transitions: " + System.String.Join(", ", available_transitions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
