//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class GetStateResponse : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/GetState";
        public override string RosMessageName => k_RosMessageName;

        //  The current state-machine state of the node.
        public StateMsg current_state;

        public GetStateResponse()
        {
            this.current_state = new StateMsg();
        }

        public GetStateResponse(StateMsg current_state)
        {
            this.current_state = current_state;
        }

        public static GetStateResponse Deserialize(MessageDeserializer deserializer) => new GetStateResponse(deserializer);

        private GetStateResponse(MessageDeserializer deserializer)
        {
            this.current_state = StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_state);
        }

        public override string ToString()
        {
            return "GetStateResponse: " +
            "\ncurrent_state: " + current_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
